# Generated by Django 2.0.1 on 2018-11-12 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20181107_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='message_html',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
